firmware update through hci
Analog-Devices-MSDK/MAX-BLE-HCI pull request #40
Opened 2024-07-26 16:24 UTC by JC-282-AD

2024-07-26 18:36 UTC, EricB-ADI reviewed
Might wanna change the output of the example to print something more professional

2024-07-26 18:42 UTC, EricB-ADI requested changes

2024-07-26 18:42 UTC, EricB-ADI commented on examples/firmware_update/README.md
You probably want to update the output to be simpler and more professional.

2024-07-26 18:42 UTC, EricB-ADI commented on src/max_ble_hci/packet_defs.py
The command is write flash not firmware update. Change the name to be accurate. Same with the erase. and the reset is a device reset not a firmware reset

2024-07-26 18:42 UTC, EricB-ADI commented on src/max_ble_hci/utils.py
What is this for?

2024-07-26 18:42 UTC, EricB-ADI commented on src/max_ble_hci/vendor_spec_cmds.py
The vendor specific commands are atomic commands. Meaning for firmware update the only thing you want is a write flash command that does the writing. The top level BLE HCI is dedictaed to add full helper functions. So add the entirety of the firmware update logic to that and only have the base write flash command in vendor specific

2024-07-26 18:42 UTC, EricB-ADI commented on src/test
remove this file

2024-07-26 18:42 UTC, EricB-ADI commented
Make sure there are no merge conflicts

2024-07-26 19:39 UTC, AbbyWolf-ADI reviewed
Make sure to run the Pylint and black-format-check workflows. I noticed some trailing whitespaces, which the black formatter will fix for you. The Pylint workflow needs to pass before we can merge in.

2024-07-26 19:39 UTC, AbbyWolf-ADI commented on src/max_ble_hci/vendor_spec_cmds.py
Agreed -- Also, check the docstring comments for `reset_device`, `erase_memory` and `update_firmware`. We use these comments to automatically generate the documentation for the HCI library, and the generator expects a specific format. The format we use is:
```
"""__function_summary__

__extended_function_summary__

Parameters
------------
__var__ : __type__
        __variable_summary__

Returns
--------
__return_type__
        __return_summary__

"""
```
Also, the first line of each should be changed from "Enable/disable ACL sink."  to a short sentence describing what the function does.

2024-07-26 19:39 UTC, AbbyWolf-ADI commented on src/max_ble_hci/utils.py
We have a utility function in **utils.py** called `_to_le_nbyte_list` which is what we typically use for little-endian conversion, I would recommend using that instead of dealing with strings.

2024-07-26 19:39 UTC, AbbyWolf-ADI commented on src/helloW.bin
This (and other binaries) probably should not be stored here. **src** contains the files which are added to site-packages when the library is installed by the user.

2024-07-26 19:39 UTC, AbbyWolf-ADI commented on src/max32655.elf
Probably should not store this file in the **src** directory

2024-07-26 19:39 UTC, AbbyWolf-ADI commented on src/output.bin
Probably should not store this file in the **src** directory

2024-07-29 15:48 UTC, JC-282-AD reviewed
all fixed~

2024-07-29 21:00 UTC, JC-282-AD commented
Remove the try catch statement in firmware_update.py. Now the HCI will return a status code before device_reset.

2024-08-19 20:40 UTC, EricB-ADI approved these changes

2024-08-19 20:41 UTC, merged